version: 2
updates:
  - package-ecosystem: npm
    directories:
      - '/'
      - '/packages/config'
      - '/packages/easter'
      - 'rites/roman1962'
      - 'rites/roman1969'
    schedule:
      interval: 'weekly'
      day: 'saturday'
      time: '00:00'
    commit-message:
      prefix: 'ci'
    labels:
      - 'dependencies'
    open-pull-requests-limit: 10
    pull-request-branch-name:
      separator: '-'
    rebase-strategy: 'auto'
  - package-ecosystem: github-actions
    directory: '/'
    schedule:
      interval: 'weekly'
      day: 'saturday'
      time: '00:00'
    commit-message:
      prefix: 'ci'
    labels:
      - 'dependencies'
    open-pull-requests-limit: 10
    pull-request-branch-name:
      separator: '-'
    rebase-strategy: 'auto'
