// AUTO-GENERATED by build/import-divinum-officium/emit-locales.ts — do not edit by hand.
// Regenerate with: npm run import:do -w @internal/rite-roman1962
import type { Locale1962 } from '../types/locale';

export const locale: Locale1962 = {
  id: 'cs-schaller',
  names: {
    common_of_abbot: 'Commune Confessoris non pontificis; Justus',
    common_of_confessor_not_pontiff: 'Commune Confessoris non pontificis; Os justi',
    common_of_dedication_of_a_church: 'Officium Dedicationis Ecclesiae',
    common_of_doctor_pontiff: 'Commune Doctoris; In medio',
    common_of_feasts_of_the_blessed_virgin_mary: 'In Festis Beatae Mariae Virginis, Salve Sancte Parens',
    common_of_many_confessor_pontiffs: 'Commune Abbatis; Os iusti II',
    common_of_many_martyrs: 'Commune Plurimorum Martyrum Sapientiam Sanctorum',
    common_of_many_martyrs_pontiffs: 'Commune Plurimorum Martyrum Intret in conspectu',
    common_of_many_virgin_martyrs: 'Commune Virginum plurimorum=Me exspectaverunt',
    common_of_non_virgins_non_martyrs: 'Commune non Virginum non Martyrum; Cognovi',
    common_of_one_confessor_pontiff: 'Commune Confessoris Pontificis;Statuit',
    common_of_one_martyr: 'Commune Unius Martyris, In virtute',
    common_of_one_supreme_pontiff_martyr: 'Commune Unius Martyris Pontificis, Sacerdotes Dei',
    common_of_one_virgin_martyr: 'Commune Virgine et martyre=Loquebar',
    common_of_supreme_pontiff_confessor: 'Commune Summorum Pontificum; Si diligis',
    common_of_virgins: 'Commune Virginum tantum; Dilexisti',
    office_of_the_dead: 'Officium Defunctorum',
    saturday_office_of_the_blessed_virgin_mary: 'Beatae Mariae Virginis in Sabbato Per annum; Salve Sancte Parens',
  },
};
