// AUTO-GENERATED by build/import-divinum-officium/emit-locales.ts — do not edit by hand.
// Regenerate with: npm run import:do -w @internal/rite-roman1962
import type { Locale1962 } from '../types/locale';

export const locale: Locale1962 = {
  id: 'cs-schaller',
  names: {
    'commune/C2a': 'Commune Unius Martyris, In virtute',
    'commune/C2b': 'Commune Unius Martyris Pontificis, Sacerdotes Dei',
    'commune/C3': 'Commune Plurimorum Martyrum Intret in conspectu',
    'commune/C3a': 'Commune Plurimorum Martyrum Sapientiam Sanctorum',
    'commune/C4': 'Commune Confessoris Pontificis;Statuit',
    'commune/C4a': 'Commune Doctoris; In medio',
    'commune/C4b': 'Commune Summorum Pontificum; Si diligis',
    'commune/C4c': 'Commune Abbatis; Os iusti II',
    'commune/C5': 'Commune Confessoris non pontificis; Os justi',
    'commune/C5b': 'Commune Confessoris non pontificis; Justus',
    'commune/C6': 'Commune Virgine et martyre=Loquebar',
    'commune/C6a': 'Commune Virginum tantum; Dilexisti',
    'commune/C6b': 'Commune Virginum plurimorum=Me exspectaverunt',
    'commune/C7a': 'Commune non Virginum non Martyrum; Cognovi',
    'commune/C8': 'Officium Dedicationis Ecclesiae',
    'commune/C9': 'Officium Defunctorum',
    'commune/C10': 'Beatae Mariae Virginis in Sabbato Per annum; Salve Sancte Parens',
    'commune/C11': 'In Festis Beatae Mariae Virginis, Salve Sancte Parens',
  },
};
