// AUTO-GENERATED by build/import-divinum-officium/emit-locales.ts — do not edit by hand.
// Regenerate with: npm run import:do -w @internal/rite-roman1962
import type { Locale1962 } from '../types/locale';

export const locale: Locale1962 = {
  id: 'cs-schaller',
  names: {
    'commune/common_of_abbot': 'Commune Confessoris non pontificis; Justus',
    'commune/common_of_confessor_not_pontiff': 'Commune Confessoris non pontificis; Os justi',
    'commune/common_of_dedication_of_a_church': 'Officium Dedicationis Ecclesiae',
    'commune/common_of_doctor_pontiff': 'Commune Doctoris; In medio',
    'commune/common_of_feasts_of_the_blessed_virgin_mary': 'In Festis Beatae Mariae Virginis, Salve Sancte Parens',
    'commune/common_of_many_confessor_pontiffs': 'Commune Abbatis; Os iusti II',
    'commune/common_of_many_martyrs': 'Commune Plurimorum Martyrum Sapientiam Sanctorum',
    'commune/common_of_many_martyrs_pontiffs': 'Commune Plurimorum Martyrum Intret in conspectu',
    'commune/common_of_many_virgin_martyrs': 'Commune Virginum plurimorum=Me exspectaverunt',
    'commune/common_of_non_virgins_non_martyrs': 'Commune non Virginum non Martyrum; Cognovi',
    'commune/common_of_one_confessor_pontiff': 'Commune Confessoris Pontificis;Statuit',
    'commune/common_of_one_martyr': 'Commune Unius Martyris, In virtute',
    'commune/common_of_one_supreme_pontiff_martyr': 'Commune Unius Martyris Pontificis, Sacerdotes Dei',
    'commune/common_of_one_virgin_martyr': 'Commune Virgine et martyre=Loquebar',
    'commune/common_of_supreme_pontiff_confessor': 'Commune Summorum Pontificum; Si diligis',
    'commune/common_of_virgins': 'Commune Virginum tantum; Dilexisti',
    'commune/office_of_the_dead': 'Officium Defunctorum',
    'commune/saturday_office_of_the_blessed_virgin_mary':
      'Beatae Mariae Virginis in Sabbato Per annum; Salve Sancte Parens',
  },
};
