// AUTO-GENERATED by build/import-divinum-officium/emit-locales.ts — do not edit by hand.
// Regenerate with: npm run import:do -w @internal/rite-roman1962
import type { Locale1962 } from '../types/locale';

export const locale: Locale1962 = {
  id: 'da',
  names: {
    'commune/common_of_abbot': 'Commune Abbatis',
    'commune/common_of_apostles': 'Commune Apostolorum',
    'commune/common_of_confessor_not_pontiff': 'Commune Confessoris non pontificis',
    'commune/common_of_dedication_of_a_church': 'Officium Dedicationis Ecclesiae',
    'commune/common_of_doctor_not_pontiff': 'Commune Doctoris non Pontificis',
    'commune/common_of_one_confessor_pontiff': 'Commune Confessoris Pontificis',
    'commune/office_of_the_dead': 'Officium Defunctorum',
    'sancti/apparition_of_saint_michael_the_archangel': 'In Apparitione S. Michaelis Archangeli',
    'sancti/dedication_of_the_archbasilica_of_saint_michael_the_archangel': 'In Dedicatione S. Michaelis Archangelis',
    'sancti/immaculate_conception_of_the_blessed_virgin_mary': 'In Conceptione Immaculata Beatae Mariae Virginis',
    'sancti/saint_ambrose_bishop_confessor_and_doctor_of_the_church':
      'S. Ambrosii Episcopi Confessoris et Ecclesiae Doctoris',
    'sancti/saint_andrew_the_apostle': 'S. Andreae Apostoli',
    'sancti/saint_bibiana_virgin_and_martyr': 'S. Bibianae Virginis Martyris',
    'sancti/saint_francis_xavier_confessor': 'S. Francisci Xaverii Confessoris',
    'sancti/saint_nicholas_bishop_and_confessor': 'S. Nicolai Episcopi et Confessoris',
    'sancti/saint_sabbas_abbot': 'S. Sabbae Abbatis',
    'sancti/saint_saturninus_martyr_rubrica1960': 'S. Saturnini Martyris',
    'tempora/advent_1_friday': 'Feria VI infra Hebdomadam I Adventus',
    'tempora/advent_1_monday': 'Feria II infra Hebdomadam I Adventus',
    'tempora/advent_1_saturday': 'Sabbato infra Hebdomadam I Adventus',
    'tempora/advent_1_sunday': 'Dominica I Adventus',
    'tempora/advent_1_thursday': 'Feria V infra Hebdomadam I Adventus',
    'tempora/advent_1_tuesday': 'Feria III infra Hebdomadam I Adventus',
    'tempora/advent_1_wednesday': 'Feria IV infra Hebdomadam I Adventus',
    'tempora/advent_2_friday': 'Feria VI infra Hebdomadam II Adventus',
    'tempora/advent_2_monday': 'Feria II infra Hebdomadam II Adventus',
    'tempora/advent_2_saturday': 'Sabbato infra Hebdomadam II Adventus',
    'tempora/advent_2_sunday': 'Dominica II Adventus',
    'tempora/advent_2_thursday': 'Feria V infra Hebdomadam II Adventus',
    'tempora/advent_2_tuesday': 'Feria III infra Hebdomadam II Adventus',
    'tempora/advent_2_wednesday': 'Feria IV infra Hebdomadam II Adventus',
  },
};
