// AUTO-GENERATED by build/import-divinum-officium/emit-locales.ts — do not edit by hand.
import type { Locale1962 } from '../types/locale';

import { locale as Cs } from './cs';
import { locale as CsSchaller } from './cs-schaller';
import { locale as Da } from './da';
import { locale as De } from './de';
import { locale as En } from './en';
import { locale as Es } from './es';
import { locale as Fr } from './fr';
import { locale as Hu } from './hu';
import { locale as It } from './it';
import { locale as La } from './la';
import { locale as Nl } from './nl';
import { locale as Pl } from './pl';
import { locale as Pt } from './pt';
import { locale as Uk } from './uk';

export const locales: Record<string, Locale1962> = {
  cs: Cs,
  'cs-schaller': CsSchaller,
  da: Da,
  de: De,
  en: En,
  es: Es,
  fr: Fr,
  hu: Hu,
  it: It,
  la: La,
  nl: Nl,
  pl: Pl,
  pt: Pt,
  uk: Uk,
};

export const localeIds = Object.keys(locales);
