// AUTO-GENERATED by build/import-divinum-officium/emit-locales.ts — do not edit by hand.
// Regenerate with: npm run import:do -w @internal/rite-roman1962
import type { Locale1962 } from '../types/locale';

export const locale: Locale1962 = {
  id: 'uk',
  names: {
    advent_1_sunday: 'Dominica I Adventus',
    advent_2_sunday: 'Dominica II Adventus',
    advent_3_sunday: 'Dominica III Adventus',
    advent_4_sunday: 'Dominica IV Adventus',
    all_saints: 'Omnium Sanctorum',
    common_of_dedication_of_a_church: 'Officium Dedicationis Ecclesiae',
    common_of_many_martyrs: 'Commune Plurimorum Martyrum',
    dedication_of_the_archbasilica_of_saint_michael_the_archangel: 'In Dedicatione S. Michælis Archangelis',
    easter_sunday: 'Dominica Resurrectionis',
    easter_time_2_sunday: 'Dominica II Post Pascha',
    easter_time_3_sunday_rubrica1960: 'Dominica III Post Pascha',
    easter_time_7_sunday: 'Dominica Pentecostes',
    epiphany_2_sunday: 'Dominica II post Epiphaniam',
    epiphany_3_sunday: 'Dominica III Post Epiphaniam',
    first_sunday_after_epiphany: 'Sanctæ Familiæ Jesu Mariæ Joseph',
    holy_family_of_jesus_mary_and_joseph: 'Dominica infra Octavam Epiphaniæ',
    nativity_of_saint_john_the_baptist: 'In Nativitate S. Johannis Baptistæ',
    office_of_the_dead: 'Officium Defunctorum',
    s_xystus_ii_pope_felicissimus_and_agapitus_martyrs_commemoration: 'свв. мчч. Ксиста 2 Папи, Феліциссима та Агапіта',
    saint_joseph_the_worker_rubrica1960: 'S. Joseph Opificis',
    saints_peter_and_paul_apostles: 'SS. Apostolorum Petri et Pauli',
    second_sunday_after_christmas: 'Sanctissimi Nominis Jesu',
    sunday_within_octave_of_christmas: 'Dominica Infra Octavam Nativitatis',
  },
};
