// AUTO-GENERATED by build/import-divinum-officium/emit-locales.ts — do not edit by hand.
// Regenerate with: npm run import:do -w @internal/rite-roman1962
import type { Locale1962 } from '../types/locale';

export const locale: Locale1962 = {
  id: 'uk',
  names: {
    'commune/common_of_dedication_of_a_church': 'Officium Dedicationis Ecclesiae',
    'commune/common_of_many_martyrs': 'Commune Plurimorum Martyrum',
    'commune/office_of_the_dead': 'Officium Defunctorum',
    'sancti/all_saints': 'Omnium Sanctorum',
    'sancti/dedication_of_the_archbasilica_of_saint_michael_the_archangel': 'In Dedicatione S. Michælis Archangelis',
    'sancti/nativity_of_saint_john_the_baptist': 'In Nativitate S. Johannis Baptistæ',
    'sancti/s_xystus_ii_pope_felicissimus_and_agapitus_martyrs_commemoration':
      'свв. мчч. Ксиста 2 Папи, Феліциссима та Агапіта',
    'sancti/saint_joseph_the_worker_rubrica1960': 'S. Joseph Opificis',
    'sancti/saints_peter_and_paul_apostles': 'SS. Apostolorum Petri et Pauli',
    'tempora/advent_1_sunday': 'Dominica I Adventus',
    'tempora/advent_2_sunday': 'Dominica II Adventus',
    'tempora/advent_3_sunday': 'Dominica III Adventus',
    'tempora/advent_4_sunday': 'Dominica IV Adventus',
    'tempora/easter_sunday': 'Dominica Resurrectionis',
    'tempora/easter_time_2_sunday': 'Dominica II Post Pascha',
    'tempora/easter_time_3_sunday_rubrica1960': 'Dominica III Post Pascha',
    'tempora/easter_time_7_sunday': 'Dominica Pentecostes',
    'tempora/epiphany_2_sunday': 'Dominica II post Epiphaniam',
    'tempora/epiphany_3_sunday': 'Dominica III Post Epiphaniam',
    'tempora/first_sunday_after_epiphany': 'Sanctæ Familiæ Jesu Mariæ Joseph',
    'tempora/holy_family': 'Dominica infra Octavam Epiphaniæ',
    'tempora/second_sunday_after_christmas': 'Sanctissimi Nominis Jesu',
    'tempora/sunday_within_octave_of_christmas': 'Dominica Infra Octavam Nativitatis',
  },
};
