// AUTO-GENERATED by build/import-divinum-officium/emit-locales.ts — do not edit by hand.
// Regenerate with: npm run import:do -w @internal/rite-roman1962
import type { Locale1962 } from '../types/locale';

export const locale: Locale1962 = {
  id: 'uk',
  names: {
    'commune/C3a': 'Commune Plurimorum Martyrum',
    'commune/C8': 'Officium Dedicationis Ecclesiae',
    'commune/C9': 'Officium Defunctorum',
    'sancti/05-01r': 'S. Joseph Opificis',
    'sancti/06-24': 'In Nativitate S. Johannis Baptistæ',
    'sancti/06-29': 'SS. Apostolorum Petri et Pauli',
    'sancti/08-06cc': 'свв. мчч. Ксиста 2 Папи, Феліциссима та Агапіта',
    'sancti/09-29': 'In Dedicatione S. Michælis Archangelis',
    'sancti/11-01': 'Omnium Sanctorum',
    'tempora/Adv1-0': 'Dominica I Adventus',
    'tempora/Adv2-0': 'Dominica II Adventus',
    'tempora/Adv3-0': 'Dominica III Adventus',
    'tempora/Adv4-0': 'Dominica IV Adventus',
    'tempora/Epi1-0': 'Sanctæ Familiæ Jesu Mariæ Joseph',
    'tempora/Epi1-0a': 'Dominica infra Octavam Epiphaniæ',
    'tempora/Epi2-0': 'Dominica II post Epiphaniam',
    'tempora/Epi3-0': 'Dominica III Post Epiphaniam',
    'tempora/Nat1-0': 'Dominica Infra Octavam Nativitatis',
    'tempora/Nat2-0': 'Sanctissimi Nominis Jesu',
    'tempora/Pasc0-0': 'Dominica Resurrectionis',
    'tempora/Pasc2-0': 'Dominica II Post Pascha',
    'tempora/Pasc3-0r': 'Dominica III Post Pascha',
    'tempora/Pasc7-0': 'Dominica Pentecostes',
  },
};
