import { RomcalTitle } from '@romcal/constants/titles/titles.type';
import { ISO8601DateString } from '@romcal/utils/type-guards/type-guards';
import { Ranks } from '@romcal/constants/ranks/ranks.enum';
import { RomcalLiturgicalColor } from '@romcal/constants/liturgical-colors/liturgical-colors.type';
import {
  RomcalLiturgicalPeriod,
  RomcalLiturgicalSeason,
} from '@romcal/constants/seasons-and-periods/seasons-and-periods.type';
import { RomcalCyclesMetadata } from '@romcal/constants/cycles/cycles.type';
import { RomcalCalendarName } from '@romcal/constants/countries/country.type';
import { Dayjs } from 'dayjs';
import { LiturgicalDay } from '@romcal/models/liturgical-day/liturgical-day.model';

export type BaseLiturgicalDay = {
  /**
   * The unique key of the liturgical day.
   */
  key: string;
  /**
   * The localized name of the liturgical day.
   */
  name: string;
  /**
   * The ISO8601 formatted date and time string of the liturgical day.
   */
  date: ISO8601DateString;
  /**
   * The rank of the liturgical day.
   */
  rank: Ranks;
  /**
   * The localized rank of the liturgical day.
   */
  rankName: string;
  /**
   * Holy days of obligation are days on which the faithful are expected to attend Mass,
   * and engage in rest from work and recreation.
   */
  isHolyDayOfObligation: boolean;
  /**
   * If this liturgical day should have always precedence, without rank consideration.
   */
  prioritized: boolean;
  /**
   * The liturgical colors of a liturgical day.
   */
  liturgicalColors: RomcalLiturgicalColor[];
  /**
   * The liturgical localized colors of a liturgical day.
   */
  liturgicalColorNames: string[];
  /**
   * Season keys to which the liturgical day is a part.
   */
  seasons: RomcalLiturgicalSeason[];
  /**
   * Season localized name to which the liturgical day is a part.
   */
  seasonNames: string[];
  /**
   * Period keys to which the liturgical day is a part.
   */
  periods: RomcalLiturgicalPeriod[];
  /**
   * Cycle metadata of a liturgical day.
   */
  cycles: RomcalCyclesMetadata;
  /**
   * Calendar metadata for the liturgical day.
   */
  calendar: RomcalCalendarMetadata;
  /**
   * The name of the calendar from which the liturgical day is defined.
   */
  fromCalendar: RomcalCalendarName;
  /**
   * The names and the object diff of the calendars from which this liturgical day is extended.
   * From the first extended definitions to the latest extended definition.
   */
  fromExtendedCalendars: LiturgyDayExtendedMetadata[];
  /**
   * The specific metadata of a liturgical day.
   */
  metadata: LiturgicalDayMetadata;
  /**
   * The base weekday or sunday on the same date that was overridden by the current liturgical day.
   */
  base?: LiturgicalDay;
};

export type LiturgicalDayArgs = Readonly<Omit<BaseLiturgicalDay, 'date'> & Partial<LiturgicalDayMetadata>> & {
  readonly date: Dayjs;
  readonly baseItem?: LiturgicalDay;
  readonly _stack: number;
};

export type BaseLiturgicalDayInput = Pick<BaseLiturgicalDay, 'key'> &
  Partial<
    Omit<
      BaseLiturgicalDay,
      | 'key'
      | 'date'
      | 'rankName'
      | 'liturgicalColors'
      | 'liturgicalColorNames'
      | 'cycles'
      | 'fromCalendar'
      | 'fromExtendedCalendars'
      | 'base'
    >
  > & {
    /**
     * The Dayjs date object of the liturgical day.
     */
    date: Dayjs;
    /**
     * The liturgical colors of a liturgical day.
     */
    liturgicalColors?: RomcalLiturgicalColor | RomcalLiturgicalColor[];
    /**
     * Cycle metadata of a liturgical day.
     */
    cycles?: Partial<RomcalCyclesMetadata>;
    /**
     * The source of the liturgical day.
     *
     * This value is used when localizing dates so that the [[Locales.localizeDates]] function knows
     * which subtree in the locale file to look for.
     *
     * A special key, "temporale", may be used when you do not wish to specify any subtree but rather
     * provide the entire path (as a period delimited string) to the [[Locales.localizeDates]] function
     * to lookup.
     */
    source?: RomcalLiturgicalDaySources;
    /**
     * If this liturgical day must be removed from this calendar and from all those it inherits,
     * on the final calendar generated by romcal.
     */
    drop?: boolean;
    /**
     * Allow to extend or replace properties of an already defined liturgical day (that have the same key).
     */
    extend?: boolean;
  };

export type LiturgicalDayExtendedInput = Omit<BaseLiturgicalDayInput, 'date' | 'extend'> &
  Partial<Pick<BaseLiturgicalDayInput, 'date'>> &
  Required<Pick<BaseLiturgicalDayInput, 'extend'>>;

/**
 * This type is used internally by romcal
 * during the construction of the liturgical calendar.
 * All properties except `key` and `date` are marked optional as
 * the the object is constructed in stages. This interface
 * should not be used in consumer applications.
 */
export type LiturgicalDayInput = BaseLiturgicalDayInput | LiturgicalDayExtendedInput;

export type LiturgyDayDiff = Partial<Pick<LiturgicalDayInput, 'name' | 'rank' | 'prioritized' | 'liturgicalColors'>> & {
  metadata?: Partial<LiturgicalDayMetadata>;
};

export type LiturgyDayExtendedMetadata = {
  fromCalendar: RomcalCalendarName;
  diff: LiturgyDayDiff;
};

export type RomcalCalendarMetadata = {
  totalWeeksInGregorianYear: number;
  totalWeeksInLiturgicalYear: number;
  weekOfGregorianYear: number;
  weekOfLiturgicalYear: number;
  weekOfSeason: number;
  dayOfGregorianYear: number;
  dayOfLiturgicalYear: number;
  dayOfSeason: number;
  dayOfWeek: number; // 0 | 1 | 2 | 3 | 4 | 5 | 6; // 0 is Sunday, 6 is Saturday
  dayOfWeekCountInMonth: number;
  startOfLiturgicalYear: Date | string;
  endOfLiturgicalYear: Date | string;
  easter: Date | string;
};

export type LiturgicalDayMetadata = {
  titles: RomcalTitle[];
};

/**
 * The source of the liturgical day.
 *
 * This value is used when localizing dates so that the [[Locales.localizeDates]] function knows
 * which subtree in the locale file to look for.
 *
 * A special key, "temporale", may be used when you do not wish to specify any subtree but rather
 * provide the entire path (as a period delimited string) to the [[Locales.localizeDates]] function
 * to lookup.
 */
export type RomcalLiturgicalDaySources =
  | 'temporale'
  | 'advent'
  | 'christmastide'
  | 'epiphany'
  | 'ordinary_time'
  | 'lent'
  | 'holy_week'
  | 'eastertide'
  | 'celebrations'
  | 'sanctorale';
