name: Romcal CI

on:
  push:
    branches: [dev, master]
  pull_request:
    types: [opened, reopened, synchronize]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  commitlint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 0
      - name: Install Node.js
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version-file: '.nvmrc'

      - name: Install Dependencies
        run: npm -q --no-progress ci --no-audit

      - name: Validate with commitlint (push)
        if: github.event_name == 'push'
        run: npx commitlint --config .config/commitlint.config.ts --last --verbose

      - name: Lint Title (pull_request)
        if: github.event_name == 'pull_request'
        env:
          TITLE: ${{ github.event.pull_request.title }}
        run: npx --no-install commitlint --config .config/commitlint.config.ts <<< "$TITLE"

  build:
    runs-on: ubuntu-latest
    needs: commitlint
    env:
      CI: true

    steps:
      - name: Git checkout dev branch
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Install Node.js
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version-file: '.nvmrc'

      # using -q to silent info outputs
      - name: Install Dependencies
        run: npm -q --no-progress ci --no-audit && npm i -g tsx

      - name: Lint and formatting
        run: npm run lint

      - name: Build
        run: npm run build

      - name: Test (no coverage)
        run: npm run test:without-coverage

      - name: Ensure Data Integrity
        run: |
          npm run data:checks
          npm run docs:check-links
          npm run docs:sort-glossary

      - name: Dry run publish
        run: tsx ./rites/roman1969/build/publish.ts --dry-run
